# SITE CONFIGURATION
base_url: "https://multimediaeval.github.io"
url: "https://multimediaeval.github.io"
title: "MediaEval Benchmark" # site's title
description: "MediaEval Benchmarking Initiative Multimedia Evaluation" # used by search engines

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: "/assets/img/twitter-card.png" # seo tag

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  avatar: assets/img/mediaeval-favicon.png
  color_image: /assets/img/lineart.png # In post when you set color
  favicon: assets/img/mediaeval-favicon.png

  # Icons
  rss: false  # Make sure you created a feed.xml with feed.xml layout
  email_address:
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "multimediaeval"
  google_plus:
  instagram:
  keybase:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: multimediaeval
  vimeo:
  wordpress:
  youtube:

  # Sharing options none
  share_buttons:
    facebook:
    twitter:
    tumblr:
    pinterest:
    pocket:
    reddit:
    linkedin:
    wordpress:
    email:

  # Scripts / Features
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Post navigation
  post_navigation: true

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll/scholar
exclude: [
        ".jekyll-cache",
        "Gemfile",
        "Gemfile.lock",
        "type-on-strap.gemspec",
        "*.gem",
        ".idea",
        "LICENSE",
        "README.md",
  ]

# theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
# remote_theme: sylhare/Type-on-Strap # If using as a remote_theme in github

collections:
  editions:
    output: true
    permalink: /:collection/:path/

# BIBLIOGRAPHY SETTINGS
scholar:
  bibliography_list_tag: ul
